// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview This file defines a Genkit flow for tagging emotions in chat responses.
 *
 * - tagChatEmotion - A function that tags the emotion of a given chat message.
 * - TagChatEmotionInput - The input type for the tagChatEmotion function.
 * - TagChatEmotionOutput - The output type for the tagChatEmotion function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const TagChatEmotionInputSchema = z.object({
  message: z.string().describe('The chat message to analyze.'),
});
export type TagChatEmotionInput = z.infer<typeof TagChatEmotionInputSchema>;

const TagChatEmotionOutputSchema = z.object({
  emotion: z.string().describe('The detected emotion in the message.'),
  confidence: z.number().describe('The confidence level of the emotion detection (0-1).'),
});
export type TagChatEmotionOutput = z.infer<typeof TagChatEmotionOutputSchema>;

export async function tagChatEmotion(input: TagChatEmotionInput): Promise<TagChatEmotionOutput> {
  return tagChatEmotionFlow(input);
}

const tagChatEmotionPrompt = ai.definePrompt({
  name: 'tagChatEmotionPrompt',
  input: {
    schema: z.object({
      message: z.string().describe('The chat message to analyze.'),
    }),
  },
  output: {
    schema: z.object({
      emotion: z.string().describe('The detected emotion in the message.'),
      confidence: z.number().describe('The confidence level of the emotion detection (0-1).'),
    }),
  },
  prompt: `Analyze the following chat message and identify the primary emotion expressed. Provide a confidence level (0-1) for your assessment.\n\nMessage: {{{message}}}\n\nRespond with the emotion and confidence level in JSON format.`,
});

const tagChatEmotionFlow = ai.defineFlow<
  typeof TagChatEmotionInputSchema,
  typeof TagChatEmotionOutputSchema
>({
  name: 'tagChatEmotionFlow',
  inputSchema: TagChatEmotionInputSchema,
  outputSchema: TagChatEmotionOutputSchema,
},
async input => {
  const {output} = await tagChatEmotionPrompt(input);
  return output!;
});